version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    restart: always

  nest-api:
    container_name: nest-api
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    env_file:
      - .env

networks:
  transcendence:
    driver: bridge