version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  svelte:
    container_name: svelte
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - nestjs-api
    env_file:
      - .env

volumes:
  postgres:
    name: nest-db